# Generated by Django 2.1.5 on 2021-07-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
    ]
